jwt {
    secret = "change-me-in-production-use-at-least-32-chars!!"
    issuer = "posly"
    audience = "posly-api"
    accessTokenExpirationMs = 900000
    refreshTokenExpirationMs = 604800000
    mfaTokenExpirationMs = 300000
}
